ErrorMessages:
  DATA 1,Normal Exit, 2,No response from modem
  DATA 3 ,Return Without GOSUB
  DATA 4 ,Out Of Data
  DATA 5 ,Illegal Function Call
  DATA 6 ,OverFlow
  DATA 7 ,Out Of Memory
  DATA 9 ,Subscript Out Of Range
  DATA 10,Duplicate Definition
  DATA 11,Division By Zero
  DATA 13,Type Mismatch
  DATA 14,Out Of String Space
  DATA 15,String Too Long
  DATA 19,No RESUME
  DATA 20,Resume Without Error
  DATA 24,Device Time Out
  DATA 25,Device Fault
  DATA 27,Out Of Paper
  DATA 50,Field Overflow
  DATA 51,Internal Error
  DATA 52,Bad File Number
  DATA 53,File Not Found
  DATA 54,Bad File Mode
  DATA 55,File Already Open
  DATA 57,Device IO Error
  DATA 58,File Already Exists
  DATA 61,Disk Full
  DATA 62,Input Past End
  DATA 63,Bad Record Number
  DATA 64,Bad File Name
  DATA 67,Too Many Files
  DATA 68,Device Unavailable
  DATA 69,Com Buffer Overflow
  DATA 70,Permission Denied
  DATA 71,Disk Not Ready
  DATA 72,Disk Media Error
  DATA 74,Rename Across Disks
  DATA 75,Path File Access Error
  DATA 76,Path Not Found
  DATA 99,System exit
  DATA 199,System abort
  DATA 201,Out Of Stack Space
  DATA 203,Mismatched Commons
  DATA 204,Mismatched Options
  DATA 205,Mismatched Revisions
  DATA 206,Invalid Program File


  DATA 100,"Invalid Line Number in GOSUB,GOTO,RETURN"
  DATA 101,"Bad arithmetic syntax"
  DATA 102,"Mismatched parenthesis"
  DATA 103,"Invalid MAP field"
  DATA 104,"Prozol stack overflow"
  DATA 105,"Lost Carrier"






  DATA 999,Unknown Error!  Contact Developer!
